### PR TITLE
Added survey results up to Aug 24

### PR DESCRIPTION
**Pull request by gtoff**
First try at adding survey results. To be discussed at next meeting

### CODE REVIEW

**Comment by gtoff** [comment]
Hi guys, here's the survey results. @mikelikesrobots I used markdown rather than react as I thought it's easier to edit for everybody, but maybe you had something else in mind

**Comment by chfritz** [comment]
Very nice! Looks good to me.

**Comment by mikelikesrobots** [comment]
Cloned it and ran it. It looks great! Good work, and please set this to open so we can approve & merge it!

**Comment by gtoff** [comment]
Done. I'll let you guys approve

**Review by chfritz — APPROVED** [review]

**Pull request merged**
